name: Deploy to AWS

on:
  workflow_dispatch_nestjs:

  push:
    branches:
      - main
    paths:
      - 'NestJsDocker/**'
      - '.github/workflow/main.yaml'

env:
  REGISTRY: ${{vars.AWS_ACCOUNT_ID}}.dkr.ecr.${{vars.AWS_REGION}}.amazonaws.com

jobs:
  build_and_push_to_ecr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to ECR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{secrets.AWS_ACCESS_KEY_ID}}
          password: ${{secrets.AWS_SECRET_ACCESS_KEY}}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          context: ./
          file: ./Dockerfile
          tags: |
            ${{ env.REGISTRY }}/nestjsdocker:latest
            ${{ env.REGISTRY }}/nestjsdocker:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push_to_ecr

    steps:
      - name: Pull latest in EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ vars.EC2_PUBLIC_IP }}
          username: 'ec2-user'
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            aws ecr get-login-password | docker login --username AWS --password-stdin ${{ env.REGISTRY }}
            docker pull ${{ env.REGISTRY }}/nestjsdocker:latest
            docker rm --force ui_app
            docker run -d --name ui_app -p 80:3000 ${{ env.REGISTRY }}/nestjsdocker:latest
